### ISSUE TITLE
Error: Too Many Requests

### ISSUE THREAD

**Issue by XhmikosR** [emedvedev/slackin-extended#20] opened 2019-10-19 15:57 UTC
I've been trying to fix our https://github.com/rauchg/slackin instance, and after spending a lot of time fixing simple but hard to spot issues, I keep getting this error. So, then I googled around and found your fork @emedvedev :)

I decided to give it a go and I'm still getting:

```
2019-10-19T15:50:35.973813+00:00 heroku[web.1]: Starting process with command `bin/slackin --coc "$SLACKIN_COC" --channels "" getbootstrap FOO`
2019-10-19T15:50:38.829158+00:00 app[web.1]: 2019-10-19T15:50:38.827Z slackin:main Theme: light
2019-10-19T15:50:38.837343+00:00 app[web.1]: 2019-10-19T15:50:38.837Z slackin:main Establishing connection with Slack
2019-10-19T15:50:38.869597+00:00 app[web.1]: 2019-10-19T15:50:38.869Z slackin:slack Fetching data from Slack
2019-10-19T15:50:38.892309+00:00 app[web.1]: 2019-10-19T15:50:38.892Z slackin:main Listening on 0.0.0.0:PORT
2019-10-19T15:50:38.953810+00:00 app[web.1]: 2019-10-19T15:50:38.953Z slackin:slack Error: Error: Too Many Requests
2019-10-19T15:50:38.953814+00:00 app[web.1]: at Request.callback (/app/node_modules/superagent/lib/node/index.js:706:15)2019-10-19T15:50:38.953816+00:00 app[web.1]: at parser (/app/node_modules/superagent/lib/node/index.js:916:18)
2019-10-19T15:50:38.953818+00:00 app[web.1]: at IncomingMessage.res.on (/app/node_modules/superagent/lib/node/parsers/json.js:19:7)
2019-10-19T15:50:38.953821+00:00 app[web.1]: at emitNone (events.js:111:20)
2019-10-19T15:50:38.953823+00:00 app[web.1]: at IncomingMessage.emit (events.js:208:7)
2019-10-19T15:50:38.953827+00:00 app[web.1]: at endReadableNT (_stream_readable.js:1064:12)
2019-10-19T15:50:38.953830+00:00 app[web.1]: at _combinedTickCallback (internal/process/next_tick.js:139:11)
2019-10-19T15:50:38.953832+00:00 app[web.1]: at process._tickCallback (internal/process/next_tick.js:181:9)
2019-10-19T15:50:38.954667+00:00 app[web.1]: 2019-10-19T15:50:38.954Z slackin:slack Attempt failed, will retry
2019-10-19T15:50:39.773455+00:00 heroku[web.1]: State changed from starting to up
2019-10-19T15:51:27.050728+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/badge.svg" host=bootstrap-slack.herokuapp.com request_id=XXX fwd="XXX" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0 protocol=https
```

Maybe the Slack API calls could be rate limited?

Thanks in advance!

PS. #19 is the other issue I hit while trying your fork.

**Comment by XhmikosR** [comment] 2019-10-19 16:00
Actually, forget about my request to add rate limiting :/ Spent too many hours on this.

I set the `SLACKIN_INTERVAL` to `300000`, but maybe I need to bump this more.

**Comment by emedvedev** [comment] 2019-10-19 18:31
I think something around `60000` should always work (refreshing numbers faster than once a minute usually isn't important anyway), although in the past even something like `5000` worked without getting rate limited. Might also depend on your subnet and whether you're using a VPN, I'm guessing, but that's just speculation.

Also, thanks a lot for the PRs! I'll try to find some time to get around to all of them tomorrow. :)

**Comment by XhmikosR** [comment] 2019-10-19 18:35
We are still hitting this, and I cannot figure out why :/

**Comment by emedvedev** [comment] 2019-10-19 18:40
Might be worth it to contact Slack support in that case. `300000` should be more than enough in my experience. Could be that some limits have changed, or maybe it is indeed your subnet.

**Comment by XhmikosR** [comment] 2019-10-19 19:14
I wonder if it has to do with the `HOSTNAME`. I remember having 503s with a Hapi.js app where I used `host: localhost` it returned 503s.

**Comment by XhmikosR** [comment] 2019-10-19 19:18
But yeah, I don't think that's the same. Here we clearly hit a limit with Slack.

**Comment by XhmikosR** [comment] 2019-10-22 19:14
@emedvedev can you reopen this please? After further debugging it appears that Slack needs a limit in our case:

```
C:\Users\xmr\Desktop>curl -d "token=xxx" -X POST https://getbootstrap.slack.com/api/users.list
{"ok":false,"error":"limit_required"}
```

I believe we need to implement [pagination](https://api.slack.com/methods/users.list#pagination)

**Comment by emedvedev** [comment] 2019-10-22 19:20
According to the help page:

> We recommend no more than 200 results at a time.

Also: 

> One day pagination will become required to use this method.

So yes, looks like pagination with 200 results at a time is a way to go. I'd still like someone from Slack to weigh in on this, but the docs are pretty clear that this is the expected behavior.

**Comment by XhmikosR** [comment] 2019-10-22 21:40
BTW we need to fix the error in this case because it does return 200 but with an error (ok: false)

**Comment by XhmikosR** [comment] 2019-10-23 08:53
Do you have suggestions about the implementation?

**Comment by XhmikosR** [comment] 2019-10-23 09:22
Reading the Slack API docs, I think we need a generic paginate function... `users` and `channels` need pagination. Also, regarding channels the docs say:

>Please note that when you are trying to page through `channels.list`, the `exclude_members` argument won't work too well with pagination at this time. Channels with very large memberships and teams with many channels may cause the method to throw HTTP 500 errors. Please exclude memberships with `exclude_members` and look them up atomically with `channels.info` instead.

And we need to take into account rate limiting

**Comment by XhmikosR** [comment] 2019-10-24 14:22
Ok, I'm genuinely stuck with this... I could use any help. I mean, we need to query the API asynchronously but without hitting the rate limit.

**Comment by XhmikosR** [comment] 2019-10-25 10:40
It seems there are deployments with many users like https://slack.rancher.io/

I wonder how they did and if we can ping them to submit a patch here.

**Comment by emedvedev** [comment] 2019-10-28 08:14
I'll probably have time to tackle this in the next couple days, once we get the current PRs merged.

**Comment by XhmikosR** [comment] 2019-10-28 10:20
Just a reminder, we also need to fix the error checking because it returns `{"ok":false,"error":"limit_required"}` but with an error code 200.

**Closed** 2020-01-10 09:40 UTC

**Comment by XhmikosR** [comment] 2021-02-13 07:56
@emedvedev I think the issue I see with the spikes in the response time etc are related to blocking the event loop and everything. If you search the codebase for `eslint`, you will see there are some suppressions that shouldn't be there.

The API should work async somehow like use the old results while fetching or something. Unfortunately, it's out of my area of expertise, but it does look like the root cause is blocking vs non-blocking.
